on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Serve ladle
        run: yarn ladle serve

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel-action@v2.5.0
