on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  lost-pixel-update:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: "lp update baseline"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
      - run: "echo Found it!"
        if: steps.check.outputs.triggered == 'true'
